name: 'utils'

  organizr:
    image: organizr/organizr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /../data/organizr:/config
    ports:
      - '80:80'
    cap_add:
      - NET_BIND_SERVICE

